var todayDate = new Date();
console.log('today Date ',todayDate);
console.log('day ',todayDate.getDay());
console.log('year ',todayDate.getFullYear());
console.log('Month ',todayDate.getMonth());
console.log('Date ',todayDate.getDate());
var constMilli = new Date(0);
console.log('Date ',todayDate.getDate());
var constString = new Date('Nov 10');
console.log('Date String Constructor ',constString);
var constYear=new Date(2017,10);
console.log('Date Year Contructor ',constYear);
